import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/app/Footer/Footer";
import "./globals.css";
import { NumProvider } from "@/context/num";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Artopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <NumProvider>
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
        </NumProvider>
      </body>
    </html>
  );
}
