import { Inter } from "next/font/google";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Artopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
